"""Configuration precedence, model isolation and source-recipe parity on CPU."""

import json
import os
import shlex
import subprocess

import pytest
import yaml

from runtime.launcher import ConfigError, ROOT, profile, read_yaml, resolve
from runtime.packaging import (
    audit_image_metadata,
    make_contract,
    owned_environment,
    payload_hashes,
)
from runtime.generate import compose, parameter_table

MODELS = ["glm53-flash", "ds4-flash", "ds4-vision", "ds41-flash", "qwen38-flash-next"]


def test_generated_files_match_the_profile_registry():
    for model in MODELS:
        expected = (
            "# Generated by python -m runtime.generate compose; requires a profile-enabled image.\n"
            + yaml.safe_dump(compose(model), sort_keys=False)
        )
        assert (ROOT / "generated" / f"{model}.compose.yaml").read_text() == expected
    expected = (
        "<!-- Generated by python -m runtime.generate table; configuration, not performance evidence. -->\n\n"
        + parameter_table()
    )
    assert (ROOT / "generated/parameters.md").read_text() == expected


def test_profile_payload_does_not_bundle_other_models_source_overlays():
    payload = payload_hashes()
    assert "lil-serve" in payload and "install.sh" in payload
    assert not any("kimi-k3" in name or "source-overlay" in name for name in payload)


@pytest.mark.parametrize(
    "filename,model,overrides",
    [
        ("qwen38-flash-next-tp2", "qwen38-flash-next", {"tp": 2}),
        ("glm53-flash-mtp3", "glm53-flash", {"mode": "mtp"}),
        ("glm53-flash-dflash2", "glm53-flash", {"mode": "dflash2"}),
    ],
)
def test_generated_mode_and_tp_examples(filename, model, overrides):
    expected = (
        "# Generated by python -m runtime.generate compose; requires a profile-enabled image.\n"
        + yaml.safe_dump(compose(model, **overrides), sort_keys=False)
    )
    assert (ROOT / "generated" / f"{filename}.compose.yaml").read_text() == expected


def test_multiple_api_keys_are_redacted():
    plan = resolve(
        "glm53-flash", env={}, argv=["--api-key", "first-private", "second-private"]
    )
    assert all(
        key not in json.dumps(plan.public())
        for key in ("first-private", "second-private")
    )


def test_recurrent_and_target_geometry_must_be_divisible():
    with pytest.raises(ConfigError, match="spacing must divide"):
        resolve("glm53-flash", env={"GLM53_MAMBA_BLOCK_SIZE": "768"})


def test_explicit_legacy_cache_path_survives_resolution():
    plan = resolve(
        "qwen38-flash-next", env={"SPARKINFER_COMPILE_CACHE_DIR": "/chosen/compile"}
    )
    assert plan.environment["SPARKINFER_COMPILE_CACHE_DIR"] == "/chosen/compile"


@pytest.mark.parametrize("model", MODELS)
@pytest.mark.parametrize("hardware", ["native", "rtx-pro-6000-pcie"])
def test_all_profiles_are_cpu_resolvable(model, hardware):
    plan = resolve(model, hardware, env={})
    assert plan.values["host"] == "0.0.0.0"
    assert plan.values["moe-backend"] == "b12x"
    assert plan.values["kv-cache-dtype"] == "fp8"
    assert plan.environment["VLLM_USE_V2_MODEL_RUNNER"] == "1"
    assert plan.argv[:5] == [
        "/opt/venv/bin/python",
        "-m",
        "vllm.entrypoints.cli.main",
        "serve",
        plan.values["model"],
    ]
    assert not any(key.startswith("--mode") for key in plan.argv)
    json.dumps(plan.public(), allow_nan=False)


@pytest.mark.parametrize("mode,depth", [("off", 0), ("mtp", 3), ("dflash2", 7)])
@pytest.mark.parametrize("dcp", [1, 4])
def test_glm_speculation_and_cache_layout_are_independent(mode, depth, dcp):
    plan = resolve(
        "glm53-flash", "rtx-pro-6000-pcie", env={"SPECULATOR": mode, "DCP": str(dcp)}
    )
    assert (
        plan.values.get("speculative-config", {}).get("num_speculative_tokens", 0)
        == depth
    )
    assert plan.environment["VLLM_B12X_MLA_CKV_GATHER"] == str(int(dcp > 1))
    assert plan.environment["VLLM_PCIE_DMA_MIN_BYTES"] == ("off" if dcp > 1 else "6MB")


def test_mtp_depth_does_not_require_cache_environment():
    first = resolve("glm53-flash", env={"MTP_DEPTH": "3"})
    second = resolve("glm53-flash", env={"MTP_DEPTH": "3", "CACHE_MODE": "vram"})
    assert first.argv == second.argv
    assert first.values["speculative-config"]["num_speculative_tokens"] == 3


def test_environment_equal_to_a_different_models_default_is_explicit():
    plan = resolve(
        "ds41-flash", env={"OMP_NUM_THREADS": "1", "MAX_CUDAGRAPH_CAPTURE_SIZE": "256"}
    )
    assert plan.environment["OMP_NUM_THREADS"] == "1"
    assert plan.values["max-cudagraph-capture-size"] == 256


def test_cli_overrides_invalid_environment_and_updates_speculative_tp():
    plan = resolve(
        "ds41-flash",
        env={"TP": "garbage", "TP_SIZE": "different"},
        argv=["--tensor-parallel-size=2"],
    )
    assert plan.values["tensor-parallel-size"] == 2
    assert plan.values["speculative-config"]["draft_tensor_parallel_size"] == 2
    assert plan.argv.count("--tensor-parallel-size") == 1


def test_settings_and_cli_environment_precedence():
    plan = resolve(
        "ds41-flash",
        env={"TP": "8", "OMP_NUM_THREADS": "8"},
        config={
            "options": {"tensor-parallel-size": 2},
            "environment": {"OMP_NUM_THREADS": "2"},
        },
        cli_env={"TP_SIZE": "4", "OMP_NUM_THREADS": "1"},
    )
    assert plan.values["tensor-parallel-size"] == 4
    assert plan.environment["OMP_NUM_THREADS"] == "1"


def test_alias_agreement_is_accepted_and_disagreement_is_rejected():
    assert (
        resolve("ds41-flash", env={"TP": "4", "TP_SIZE": "4"}).values[
            "tensor-parallel-size"
        ]
        == 4
    )
    with pytest.raises(ConfigError, match="Conflicting environment aliases"):
        resolve("ds41-flash", env={"TP": "2", "TP_SIZE": "4"})


@pytest.mark.parametrize(
    "arguments",
    [
        ["--max-num-seqs", "4", "--max_num_seqs=8"],
        ["--enable-prefix-caching", "--no-enable-prefix-caching"],
    ],
)
def test_duplicate_cli_options_are_rejected(arguments):
    with pytest.raises(ConfigError, match="only once"):
        resolve("glm53-flash", env={}, argv=arguments)


def test_json_root_replacement_and_field_override():
    plan = resolve(
        "glm53-flash",
        env={},
        argv=[
            "--compilation-config",
            '{"cudagraph_mode":"FULL"}',
            "--compilation-config.custom_ops",
            '["all"]',
            "--default-chat-template-kwargs.clear_thinking=true",
        ],
    )
    assert plan.values["compilation-config"] == {
        "cudagraph_mode": "FULL",
        "custom_ops": ["all"],
    }
    assert plan.values["default-chat-template-kwargs"]["clear_thinking"] is True
    assert plan.argv.count("--compilation-config") == 1


def test_explicit_speculation_json_owns_method_and_depth():
    plan = resolve(
        "glm53-flash",
        env={"MTP_DEPTH": "3"},
        argv=[
            "--speculative-config",
            '{"method":"dflash","num_speculative_tokens":7,"model":"draft/repository"}',
        ],
    )
    assert plan.values["mode"] == "dflash2"
    assert "VLLM_B12X_NVFP4_ACTIVATION_MODE" not in plan.environment
    assert plan.values["speculative-config"]["model"] == "draft/repository"


def test_graph_cap_override_prunes_only_profile_capture_defaults():
    plan = resolve("glm53-flash", env={"MAX_CUDAGRAPH_CAPTURE_SIZE": "64"})
    assert max(plan.values["cudagraph-capture-sizes"]) == 64
    with pytest.raises(ConfigError, match="Capture sizes"):
        resolve(
            "glm53-flash",
            env={
                "MAX_CUDAGRAPH_CAPTURE_SIZE": "64",
                "CUDAGRAPH_CAPTURE_SIZES": "1 128",
            },
        )


def test_aligned_recurrent_spacing_does_not_shrink_attention_pages():
    plan = resolve(
        "glm53-flash",
        env={"GLM53_MAMBA_BLOCK_SIZE": "256"},
        argv=["--recurrent-checkpoint-policy", "aligned", "--prefix-match-unit", "256"],
    )
    assert plan.environment["VLLM_GLM53_SPLIT_TARGET_BLOCK_SIZE"] == "2048"
    assert plan.environment["VLLM_GLM53_SPLIT_MAMBA_BLOCK_SIZE"] == "256"
    assert plan.values["prefix-cache-retention-interval"] == "None"
    assert plan.values["max-parallel-prefills"] == 1


def test_only_prefix_match_unit_does_not_claim_stored_checkpoints():
    plan = resolve("glm53-flash", env={}, argv=["--prefix-match-unit=256"])
    assert plan.values["recurrent-checkpoint-policy"] == "request_boundaries"
    assert plan.environment["VLLM_GLM53_SPLIT_MAMBA_BLOCK_SIZE"] == "auto"


@pytest.mark.parametrize("memory", ["ram", "disk"])
def test_engram_is_table_placement_not_cpu_offload(memory):
    config = resolve("ds41-flash", env={"ENGRAM_TABLE_MEMORY": memory}).values[
        "engram-config"
    ]
    assert config == {
        "cpu_offload": False,
        "table_memory": memory,
        "disk_resident_scales": False,
        "projection_tp": False,
    }


def test_qwen_private_head_and_ple_are_preserved_without_glm_environment():
    plan = resolve("qwen38-flash-next", env={})
    assert plan.environment["VLLM_MTP_NVFP4_LM_HEAD"] == "1"
    assert plan.environment["VLLM_LM_HEAD_A16"] == "1"
    assert plan.environment["VLLM_PLE_CPU_OFFLOAD"] == "1"
    assert plan.values["max-num-batched-tokens"] == 6019
    assert not any(key.startswith("VLLM_GLM53_") for key in plan.environment)


def test_ds4_keeps_native_dense_selection_and_accepts_explicit_deepgemm():
    default = resolve("ds4-flash", env={})
    assert "linear-backend" not in default.values
    explicit = resolve("ds4-flash", env={}, argv=["--linear-backend", "deep_gemm"])
    assert explicit.values["linear-backend"] == "deep_gemm"
    assert explicit.environment["VLLM_B12X_MOE_FP4_FORCE_A16"] == "0"
    assert default.values["max-cudagraph-capture-size"] == 48
    assert resolve("ds4-vision", env={}).values["max-cudagraph-capture-size"] == 16


@pytest.mark.parametrize(
    "arguments",
    [
        ["--decode-context-parallel-size", "3"],
        ["--port", "0"],
        ["--gpu-memory-utilization", "nan"],
        ["--max-num-seqs", "0"],
        ["--prefill-schedule-interval", "8"],
        ["--prefill-compute-half-life", "smooth"],
        ["--cudagraph-capture-sizes", "4", "2"],
        ["--max-parallel-prefills", "0"],
        ["--draft-tokens", "-1"],
        ["--kv-cache-dtype", "nvfp4_ds_mla"],
        ["--compilation-config", '{"x":NaN}'],
        ["--config", "arbitrary.yaml"],
    ],
)
def test_invalid_effective_combinations_fail(arguments):
    with pytest.raises(ConfigError):
        resolve("glm53-flash", env={}, argv=arguments)


@pytest.mark.parametrize("half_life", ["smooth", "responsive", "0.5", "2"])
def test_auto_fairness_uses_native_options_without_reimplementing_controller(half_life):
    plan = resolve(
        "glm53-flash",
        env={
            "PREFILL_COMPUTE_SHARE": "auto",
            "PREFILL_COMPUTE_HALF_LIFE": half_life,
            "MAX_PARALLEL_PREFILLS": "auto",
            "PREFILL_POLICY": "decode-aware",
            "DECODE_REFILL_TARGET": "auto",
        },
    )
    assert plan.values["max-parallel-prefills"] == "auto"
    assert plan.values["decode-refill-target"] == "auto"


@pytest.mark.parametrize(
    "environment",
    [
        {"CACHE_MODE": "lmcache"},
        {"LMCACHE_MODE": "ram"},
        {"LMCACHE_ENABLED": "1"},
        {"CACHE_MODE": "native"},
    ],
)
def test_external_cache_cannot_silently_fall_back_to_gpu_cache(environment):
    with pytest.raises(ConfigError):
        resolve("glm53-flash", env=environment)


def test_unknown_native_arguments_and_logging_are_preserved():
    plan = resolve(
        "ds41-flash",
        env={"VLLM_LOGGING_LEVEL": "DEBUG", "NCCL_GRAPH_FILE": "/topology/real.xml"},
        argv=["--some-native-feature", "literal value", "--another=1"],
    )
    assert plan.argv[-3:] == ["--some-native-feature", "literal value", "--another=1"]
    assert plan.environment["VLLM_LOGGING_LEVEL"] == "DEBUG"
    assert plan.environment["NCCL_GRAPH_FILE"] == "/topology/real.xml"
    assert (
        "NCCL_GRAPH_FILE"
        not in resolve("ds41-flash", env={"NCCL_GRAPH_FILE": ""}).environment
    )


def test_config_print_redacts_secrets_without_altering_execution_values():
    plan = resolve(
        "glm53-flash",
        env={"HF_TOKEN": "never-print-this"},
        config={"environment": {"SERVICE_API_KEY": "private-file-value"}},
        argv=[
            "--api-key",
            "private-api-value",
            "--additional-config",
            '{"authorization":"private-json-value"}',
        ],
    )
    output = json.dumps(plan.public())
    assert all(
        secret not in output
        for secret in (
            "never-print-this",
            "private-file-value",
            "private-api-value",
            "private-json-value",
        )
    )
    assert "private-api-value" in plan.argv


def test_cache_namespaces_follow_runtime_and_profile_not_a_release_string():
    first = resolve("qwen38-flash-next", env={}, runtime_identity="a" * 64)
    second = resolve("qwen38-flash-next", env={}, runtime_identity="b" * 64)
    assert first.environment["VLLM_CACHE_ROOT"] != second.environment["VLLM_CACHE_ROOT"]
    explicit = resolve(
        "qwen38-flash-next",
        env={"XDG_CACHE_HOME": "/custom", "TRITON_CACHE_DIR": "/explicit"},
    )
    assert explicit.environment["VLLM_CACHE_ROOT"] == "/custom/vllm"
    assert explicit.environment["TRITON_CACHE_DIR"] == "/explicit"


def test_duplicate_yaml_and_path_traversal_are_rejected(tmp_path):
    duplicate = tmp_path / "duplicate.yaml"
    duplicate.write_text("options: {}\noptions: {}\n")
    with pytest.raises(ConfigError, match="Duplicate"):
        read_yaml(duplicate)
    with pytest.raises(ConfigError):
        profile("model", "../../secrets")


def test_image_metadata_cannot_disguise_inherited_model_defaults():
    metadata = {
        "Id": "sha256:" + "1" * 64,
        "Config": {"Env": ["PATH=/opt/venv/bin", "CUDA_HOME=/usr/local/cuda"]},
    }
    audit_image_metadata(metadata)
    contract = make_contract(metadata, "2" * 64)
    assert contract["files"] == payload_hashes()
    assert not contract["qualified_serving_receipts"]
    metadata["Config"]["Env"].append("OMP_NUM_THREADS=1")
    with pytest.raises(ConfigError, match="OMP_NUM_THREADS"):
        audit_image_metadata(metadata)
    assert "VLLM_GLM53_MTP_DRAFT_HEAD" in owned_environment()


@pytest.mark.parametrize("model", MODELS)
def test_compose_has_no_second_kernel_policy_copy(model):
    document = compose(model)
    service = document["services"]["model"]
    assert not any(
        key.startswith(("VLLM_", "B12X_", "NCCL_")) for key in service["environment"]
    )
    assert service["entrypoint"] == ["/usr/local/bin/lil-serve"]
    assert len(
        service["deploy"]["resources"]["reservations"]["devices"][0]["device_ids"]
    ) == int(service["environment"]["TP"])
    assert model in parameter_table()


def test_glm_base_recipe_semantic_parity_for_model_arguments():
    """Compare actual Bash DRY_RUN output; do not start an engine or import torch."""
    script = ROOT.parent / "recipes/glm53/serve-glm53-flash-nvfp4-dflash2.sh"
    result = subprocess.run(
        ["bash", str(script)],
        env={
            "PATH": os.environ["PATH"],
            "DRY_RUN": "1",
            "NUM_SPECULATIVE_TOKENS": "3",
            "MAX_CUDAGRAPH_CAPTURE_SIZE": "256",
            "PREFILL_SCHEDULE_INTERVAL": "1",
        },
        text=True,
        capture_output=True,
        check=True,
    )
    legacy = shlex.split(result.stdout.split("launch:", 1)[1])
    plan = resolve("glm53-flash", env={"MTP_DEPTH": "3"})
    for name in (
        "model",
        "tensor-parallel-size",
        "decode-context-parallel-size",
        "max-num-batched-tokens",
        "block-size",
        "max-model-len",
        "moe-backend",
        "linear-backend",
        "additional-config",
        "compilation-config",
        "speculative-config",
        "default-chat-template-kwargs",
        "override-generation-config",
    ):
        if name == "model":
            assert legacy[2] == plan.values[name]
            continue
        value = legacy[legacy.index("--" + name) + 1]
        resolved = plan.values[name]
        assert (
            json.loads(value) == resolved
            if isinstance(resolved, dict)
            else value == str(resolved)
        )
