#!/usr/bin/env python3
"""Create deterministic wheels from hash-verified installed distributions.

An immutable container can contain a qualified package after its source wheel
was created and removed in one image layer. Docker cannot recover such a wheel
from layer history. This tool verifies every hashed installed file recorded by
the distribution, excludes installation-generated metadata and bytecode, and
packs the remaining qualified payload into a distributable wheel.
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import importlib.metadata
import json
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path, PurePosixPath


INSTALLATION_METADATA = {"INSTALLER", "RECORD", "REQUESTED", "direct_url.json"}


def sha256(path: Path) -> str:
    """Return the hexadecimal SHA-256 digest of one file."""
    digest = hashlib.sha256()
    with path.open("rb") as source:
        while chunk := source.read(8 * 1024 * 1024):
            digest.update(chunk)
    return digest.hexdigest()


def record_digest(path: Path) -> str:
    """Return the URL-safe base64 SHA-256 value used in wheel RECORD files."""
    raw = bytes.fromhex(sha256(path))
    return base64.urlsafe_b64encode(raw).decode("ascii").rstrip("=")


def is_installation_generated(path: PurePosixPath) -> bool:
    """Return whether a RECORD entry was generated by wheel installation."""
    return (
        ".." in path.parts
        or "__pycache__" in path.parts
        or path.suffix == ".pyc"
        or (".dist-info" in path.parent.name and path.name in INSTALLATION_METADATA)
    )


def normalize_tree_mtime(root: Path, epoch: int) -> None:
    """Set a stable timestamp on every staged directory and regular file."""
    for path in sorted(root.rglob("*"), reverse=True):
        if path.is_symlink():
            continue
        os.utime(path, (epoch, epoch))
    os.utime(root, (epoch, epoch))


def repack_distribution(name: str, output_dir: Path, epoch: int) -> dict[str, object]:
    """Verify and repack one installed distribution into ``output_dir``."""
    distribution = importlib.metadata.distribution(name)
    files = distribution.files
    if files is None:
        raise RuntimeError(f"distribution has no RECORD file list: {name}")
    source_record = Path(distribution._path) / "RECORD"
    if not source_record.is_file():
        raise RuntimeError(f"distribution RECORD is absent: {name}")

    copied: list[str] = []
    skipped: list[str] = []
    with tempfile.TemporaryDirectory(prefix=f"repack-{name}-") as temporary:
        stage = Path(temporary) / "payload"
        stage.mkdir()
        for package_path in files:
            relative = PurePosixPath(str(package_path))
            source = Path(distribution.locate_file(package_path))
            if not source.is_file():
                raise RuntimeError(f"installed RECORD path is absent: {relative}")
            if package_path.hash is not None:
                if (
                    package_path.hash.mode != "sha256"
                    or record_digest(source) != package_path.hash.value
                ):
                    raise RuntimeError(f"installed RECORD digest mismatch: {relative}")
            if is_installation_generated(relative):
                skipped.append(str(relative))
                continue
            destination = stage.joinpath(*relative.parts)
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(source, destination)
            shutil.copymode(source, destination)
            copied.append(str(relative))

        normalize_tree_mtime(stage, epoch)
        before = set(output_dir.glob("*.whl"))
        environment = os.environ.copy()
        environment["SOURCE_DATE_EPOCH"] = str(epoch)
        subprocess.run(
            [
                sys.executable,
                "-m",
                "wheel",
                "pack",
                "--dest-dir",
                str(output_dir),
                str(stage),
            ],
            check=True,
            env=environment,
            stdout=sys.stderr,
        )
        produced = set(output_dir.glob("*.whl")) - before
        if len(produced) != 1:
            raise RuntimeError(f"wheel pack produced {len(produced)} files for {name}")
        wheel = produced.pop()

    return {
        "name": distribution.metadata["Name"],
        "version": distribution.version,
        "source_record_sha256": sha256(source_record),
        "copied_file_count": len(copied),
        "skipped_installation_file_count": len(skipped),
        "wheel": wheel.name,
        "wheel_sha256": sha256(wheel),
    }


def main() -> None:
    """Repack requested packages and write their provenance manifest."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--source-date-epoch", type=int, required=True)
    parser.add_argument("package", nargs="+")
    args = parser.parse_args()
    args.output_dir.mkdir(parents=True, exist_ok=True)
    results = [
        repack_distribution(package, args.output_dir, args.source_date_epoch)
        for package in args.package
    ]
    print(
        json.dumps(
            {
                "schema": "local-inference-installed-distribution-repack/v1",
                "status": "implemented",
                "packages": results,
            },
            indent=2,
            sort_keys=True,
        )
    )


if __name__ == "__main__":
    main()
